---
output: html_document
---
```{r , include = FALSE}
library(data.table)
library(dplyr)
library(lubridate)
library(daymetr)
library(rjson)
library(bitops)
library(RCurl)
library(phenocamapi)
library(ggplot2)
library(devtools)
library(plotly)
source('~/Projects/niwot_grvi_gcc/funcs.R')
```

  
```{r, echo = FALSE, warning=FALSE, fig.width = 12, fig.height = 4, out.width = "100%"}
# read in timeseries data
# 3 day only
xxx <- 'nuExG'

plot_roi('austincary_EN_1000', xxx = xxx)
plot_roi('canadaOBS_EN_1000', xxx = xxx)
plot_roi('chibougamau_EN_1000', xxx = xxx)

# plot_roi('howland1_EN_1000', xxx = xxx)
# plot_roi('howland1_EN_2000', xxx = xxx)
plot_roi('howland1_EN_3000', xxx = xxx)

# plot_roi('niwot2_EN_1000', xxx = xxx)
plot_roi('niwot3_EN_1000', xxx = xxx)
# plot_roi('niwot4_EN_1000', xxx = xxx)

# plot_roi('niwot4_EN_2000', xxx = xxx)
# plot_roi('niwot5_EN_1000', xxx = xxx)
# plot_roi('niwotridge_EN_1000', xxx = xxx)

plot_roi('oregonMP_EN_1000', xxx = xxx)
plot_roi('oregonYP_EN_1000', xxx = xxx)
plot_roi('oregonYP_EN_2000', xxx = xxx)

# plot_roi('oregonmp1_EN_1000', xxx = xxx)
plot_roi('turkeypointenf02_EN_1000', xxx = xxx)
plot_roi('turkeypointenf39_EN_1000', xxx = xxx)

plot_roi('turkeypointenf74_EN_1000', xxx = xxx)
plot_roi('vancouverisland_EN_1000', xxx = xxx)
plot_roi('vancouverisland_EN_2000', xxx = xxx)

```